name: API Testing Framework
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
    - run: wget -O /path/to/chromedriver https://chromedriver.storage.googleapis.com/LATEST_RELEASE/chromedriver_linux64.zip

    - run: unzip /path/to/chromedriver.zip -d /path/to/chromedriver

    - run: mvn test -DsuiteXmlFile=src/test/resources/tests


